# Generated by Django 4.2.23 on 2025-08-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('adress', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('membership_type', models.CharField(max_length=40)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('due_ammount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('joining_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
