# Generated by Django 4.2.23 on 2025-08-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='due_ammount',
            new_name='due_amount',
        ),
    ]
