# Generated by Django 4.2.23 on 2025-08-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_member_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('joining_date', models.DateField()),
                ('job_post', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
