# Generated by Django 4.2.23 on 2025-08-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_staff_active_staff_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20)),
                ('staff_name', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=100)),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_date', models.DateField()),
                ('salary_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
