# Generated by Django 4.2.23 on 2025-08-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_staffsalary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('member_id', models.CharField(max_length=50, unique=True)),
                ('membership_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('job_role', models.CharField(choices=[('Trainer', 'Trainer'), ('Receptionist', 'Receptionist'), ('Cleaner', 'Cleaner'), ('Admin', 'Admin')], max_length=50)),
                ('account_number', models.CharField(max_length=18)),
                ('bank_name', models.CharField(max_length=100)),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cheque', 'Cheque')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
