# Generated by Django 4.2.23 on 2025-08-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_memberinvoice_staffinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinvoice',
            name='job_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
