# Generated by Django 4.2.23 on 2025-08-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_staffinvoice_job_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinvoice',
            name='membership_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffinvoice',
            name='payment_mode',
            field=models.CharField(max_length=50),
        ),
    ]
