# Generated by Django 4.2.23 on 2025-08-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_membershipplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('large_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
