# Generated by Django 4.2.23 on 2025-09-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_useraccount_about_useraccount_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
            ],
        ),
    ]
