# Generated by Django 4.2.23 on 2025-09-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_supplementsale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplementSale',
        ),
    ]
