# Generated by Django 4.2.23 on 2025-09-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_images/'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
