# Generated by Django 4.2.23 on 2025-09-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_staff_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='assigned_pages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
