# Generated by Django 4.2.23 on 2025-09-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_dummy_delete_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dummy',
        ),
    ]
